name: Chrome Extension CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Cache node modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-

    - name: Install dependencies
      run: yarn install

    - name: Run unit tests
      run: yarn test

    - name: Build extension
      run: yarn build

    - name: Package extension
      run: |
        zip -r chrome-extension.zip dist

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: chrome-extension
        path: chrome-extension.zip
